name: Post RSS to Bluesky

on:
  schedule:
    - cron: "0 */2 * * *"  # Runs every 2 hours
  workflow_dispatch:  # Allow manual runs

jobs:
  post-news:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Restore posted_news.json cache
        uses: actions/cache@v3
        with:
          path: posted_news.json
          key: posted-news-cache
          restore-keys: |
            posted-news-cache-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
        run: python rss_to_bluesky.py

      - name: Save posted_news.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add posted_news.json
          git commit -m "Update posted_news.json to track posted news" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
